version: '3.5'

services: 
    bot:
        build: .
        container_name: "payload"
        restart: always
        env_file: 
            - ./config.env
        ports: 
            - 3000:3000
        depends_on: 
            - mongo
        links: 
            - mongo
            
    mongo:
        container_name: "mongo"
        image: mongo
        restart: always
        ports: 
            - 27017-27019:27017-27019
        volumes: 
            - ./mongo:/data/db
        env_file: 
            - ./config.env