version: '3.5'

services: 
    bot:
        build: .
        container_name: "payload-prod"
        restart: always
        env_file: 
            - ./.env
        ports: 
            - 3000:3000
        depends_on: 
            - mongo
        links: 
            - mongo
            
    mongo:
        container_name: "mongo-prod"
        image: mongo
        restart: always
        ports: 
            - 27017-27019:27017-27019
        volumes: 
            - /opt/production/mongo:/data/db
        env_file: 
            - ./.env
