version: '3.5'

services: 
    bot:
        image: "node:12"
        command: "npm run start"
        working_dir: /home/payload
        container_name: "payload"
        volumes: 
            - .:/home/payload
        restart: always
        ports: 
            - 3000:3000
        depends_on: 
            - mongo
        links: 
            - mongo
            
    mongo:
        container_name: "mongo"
        image: mongo
        restart: always
        ports: 
            - 27017-27019:27017-27019
        volumes: 
            - ./mongo:/data/db
        env_file: 
            - ./config.env

    mongo-express:
        image: mongo-express
        container_name: "mongoexpress"
        restart: always
        ports:
            - 8081:8081
        env_file: 
            - ./config.env
        depends_on: 
            - mongo
        links: 
            - mongo
volumes:
  mongo: ~